### ISSUE TITLE
Create Vagrantfile

### ISSUE THREAD

**Issue by PokerMao** [DevOps17-Bravo/orders#1]
**As a** Developer, 
**I need** to create Vagrantfiles, 
**so that** everyone can use the same developing environment for the project

**Assumption**:

- Need to figure out what we need in our vagrantfile

**Acceptance Criteria**:

  **Given** the vagrant file 
  **when** developers run vagrant up and vagrant ssh
  **Then** developers can access the environment and start developing

**Comment by ZhuDailing** [comment]
:D

**Comment by qianransun** [comment]
cool~

**Comment by Qinxintan** [comment]
next is to add docker container
