### ISSUE TITLE
Create a New Order

### ISSUE THREAD

**Issue by ZhuDailing** [DevOps17-Bravo/orders#12]
**As a** customer
**I need to** create a new order after a checkout was finished
**So that** I am able to store and learn all the information the order contains

**Assumption**:

- The developer has all the information the order format has

**Acceptance Criteria**:

**Given that** I am a customer with all the information the order format has
**When** I finishes my checkout process 
**Then** I create a order with all the details this order contains including customer id and order id etc.

**Comment by PokerMao** [comment]
I'll start by writing tests and then I'll implement the fucntion
