### ISSUE TITLE
Order Schema

### ISSUE THREAD

**Issue by markmty** [DevOps17-Bravo/orders#17]
**As a** developer
**I need** to design the standard schema for order in the database
**So that** customers can get certain information from an order

**Assumptions:**
- Information of orders is accessible
- Database is accessible

**Acceptance Criteria**

**Given** those information of an order
**When** customers create an order
**Then** that order can be added to the database with such schema

**Comment by markmty** [comment]
Since this requires the creation of the database, I suppose more points should be assigned to this story

**Comment by PokerMao** [comment]
Great point!

**Comment by PokerMao** [comment]
The schema design has been finalized. It's as the following:
orderId : string
items : list<itemId>
orderTotal: int
orderTime: string

**Comment by markmty** [comment]
That seems cool!

**Comment by Qinxintan** [comment]
you missed customerId

**Comment by Qinxintan** [comment]
we can ignore items now since we haven't talked with items' team.

**Comment by PokerMao** [comment]
Thanks for bringing this up! I've changed it to:
order_id : string
customer_id : string
order_total : int
order_time : string
