### ISSUE TITLE
Create a code skeleton

### ISSUE THREAD

**Issue by PokerMao** [DevOps17-Bravo/orders#7]
**As a** Developer
**I need** some starter code
**So that** I can start adding feature to it

**Assumptions:**

1. There's general skeleton code for us

**Acceptance Criteria:**
Given specific function implementation
When we have the specific implementation
Then properly insert the function in the base skeleton

**Comment by Qinxintan** [comment]
Start developing by creating the TDD test_xxx.py files that contains your Unit Tests to test your service and model.
